### ISSUE TITLE
Extension not working when there's import type in the file

### ISSUE THREAD

**Issue by orenklein** [Agreon/styco#31]
if you try to use the styco command in the following file you'll get `unexpected token (2:12)`
```typescript
import React from "react";
import type { CSSProperties } from "react";

export const MyComp = () => {

  return (
    <div style={{display:"grid"}}/>
  );
};
```

**Comment by Agreon** [comment]
Thanks for letting me know! I'll have a look

**Comment by orenklein** [comment]
Thanks for the quick response and fix! It's working great :)

**Comment by Agreon** [comment]
Glad to here that, always happy to help :)
