### ISSUE TITLE
Support for object syntax

### ISSUE THREAD

**Issue by schpet** [Agreon/styco#35]
styled-components / emotion supports an object syntax, which in some places like react-native can be compelling.

e.g. instead of this:

```tsx
const LogoContainer = styled(Box)`
  margin-top: 122px;
  margin-bottom: 56px;
`
```

generate this:

```tsx
const LogoContainer = styled(Box)({
  marginTop: "122px",
  marginBottom: "56px"
})
```

would y'all be open to adding support for this? e.g. another configuration option like `objectSyntax` (default: false)

**Comment by Agreon** [comment]
Hey! Good idea! I'll have a look asap.

**Comment by Agreon** [comment]
Should be available soon ;)
