### ISSUE TITLE
Add option to sort the styles of the created component

### ISSUE THREAD

**Issue by Agreon** [Agreon/styco#7]

**Comment by john-nhoj** [comment]
@Agreon , I am interested in working on this enhancement. Can you describe a bit more what you expect?

Imo, there are 2 ways to implement it:
1. Add the possibility for the user to run `Styco and sort styles` on top of the standard `Styco`
2. Add the possibility for the user to run something like `Sort all styles` and then look up all the styled-components and sort the styles.

Of course, the first possibility is easier to implement but I'd like to hear your opinion :)

**Comment by Agreon** [comment]
Hey, thanks for your interest!

The idea would be to let the user specify in the settings if he wants the created styled components to be sorted by style-key.
The sorting should be happening somewhre around https://github.com/Agreon/styco/blob/master/src/extension.ts#L178 i guess.
